name: prepare_release
description: Prepare React Native release
runs:
  using: composite
  steps:
    - name: Yarn Install
      shell: bash
      run: yarn install --non-interactive
    - name: Versioning workspace packages
      shell: bash
      run: |
        node scripts/releases/set-version "${{ inputs.version }}"
    - name: Creating Release commit
      shell: bash
      run: |
        git commit -a -m "Release ${{ inputs.version }}" -m "#publish-packages-to-npm&${{ inputs.tag }}"
        git tag -a "v${{ inputs.version }}" -m "v${{ inputs.version }}"
        GIT_PAGER=cat git show HEAD
    - name: Update latest if needed
      shell: bash
      if: ${{ inputs.tag == 'latest' }}
      run: |
        git tag -d "latest"
        git push origin :latest
        git tag -a "latest" -m "latest"
    - name: Pushing release commit
      shell: bash
      run: |
        git push origin $CIRCLE_BRANCH --follow-tags
